server:
  port: 9001
spring:
  application:
    name: cloud-alibaba-provider
  cloud:
    nacos:
      server-addr: 192.168.74.123:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'